# Generated by Django 5.1 on 2024-08-07 20:29

import django_countries.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0002_alter_user_options_remove_user_username_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="country",
            field=django_countries.fields.CountryField(
                blank=True, default="RU", max_length=2, null=True, verbose_name="Страна"
            ),
        ),
    ]
