# Generated by Django 5.1 on 2024-08-20 16:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0008_subscription"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Subscription",
        ),
    ]
