# Generated by Django 5.1 on 2024-08-23 13:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0011_alter_payment_amount"),
    ]

    operations = [
        migrations.RenameField(
            model_name="payment",
            old_name="amount",
            new_name="price",
        ),
    ]
