# Generated by Django 5.1 on 2024-08-23 14:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0012_rename_amount_payment_price"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="payment",
            name="price",
        ),
    ]
