# Generated by Django 5.1 on 2024-08-07 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("lms", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="course",
            name="preview",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to="courses/preview/",
                verbose_name="Изображение",
            ),
        ),
        migrations.AlterField(
            model_name="lesson",
            name="preview",
            field=models.ImageField(
                upload_to="lessons/preview/", verbose_name="Изображение"
            ),
        ),
    ]
