# Generated by Django 5.1 on 2024-08-22 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("lms", "0008_alter_subscription_unique_together"),
    ]

    operations = [
        migrations.AddField(
            model_name="course",
            name="price",
            field=models.DecimalField(
                decimal_places=2,
                default=10000.0,
                max_digits=15,
                verbose_name="Стоимость",
            ),
        ),
    ]
