# Generated by Django 5.1 on 2024-08-22 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("lms", "0009_course_price"),
    ]

    operations = [
        migrations.AlterField(
            model_name="course",
            name="price",
            field=models.IntegerField(default=10000, verbose_name="Стоимость"),
        ),
    ]
