# Generated by Django 5.1 on 2024-08-22 20:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("lms", "0010_alter_course_price"),
    ]

    operations = [
        migrations.AddField(
            model_name="course",
            name="stripe_price_id",
            field=models.CharField(
                blank=True, max_length=100, null=True, verbose_name="stripe_price_id"
            ),
        ),
        migrations.AddField(
            model_name="course",
            name="stripe_product_id",
            field=models.CharField(
                blank=True, max_length=100, null=True, verbose_name="stripe_product_id"
            ),
        ),
    ]
