# Generated by Django 5.1 on 2024-08-22 21:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("lms", "0011_course_stripe_price_id_course_stripe_product_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="course",
            name="price",
            field=models.PositiveIntegerField(default=10000, verbose_name="Стоимость"),
        ),
    ]
