# Generated by Django 5.1 on 2024-08-22 22:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("lms", "0012_alter_course_price"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="course",
            name="stripe_price_id",
        ),
        migrations.RemoveField(
            model_name="course",
            name="stripe_product_id",
        ),
    ]
