# Generated by Django 5.1 on 2024-08-27 21:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("lms", "0013_remove_course_stripe_price_id_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="course",
            name="last_updated",
            field=models.DateTimeField(
                auto_now=True, verbose_name="Дата последнего изменения"
            ),
        ),
    ]
